title: "docs.cloudpilgrim.io"
remote_theme: pmarsceill/just-the-docs
color_scheme: "nil"

# Enable or disable the site search function (true/false)
search_enabled: true

# Enable or disable heading anchor
heading_anchors: true

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile", "CNAME"]

aux_links:
  "https://github.com/fichardfurniss96/documentation":
    - "//github.com/richardfurniss96/documentation"
