title: "docs.cloudpilgrim.io"
remote_theme: pmarsceill/just-the-docs
color_scheme: "nil"

# Enable or disable the site search function (true/false)
search_enabled: true

# Enable or disable heading anchor
heading_anchors: true
